# Generated by Django 3.1.2 on 2020-10-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201022_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='statics/category/'),
        ),
    ]
